application: lightscript-net
version: 1
runtime: python
api_version: 1

handlers:

- url: /javadoc
  static_dir: javadoc

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /roadmap.html
  static_files: roadmap.html
  upload: roadmap.html

- url: /README.pdf
  static_files: README.pdf
  upload: README.pdf

- url: /.*
  static_files: index.html
  upload: index.html
